package il.ac.bgu.cnfCompilation

import il.ac.bgu.failureModel.NoEffectFailureModel
import il.ac.bgu.failureModel.VariableModelFunction
import org.agreement_technologies.common.map_planner.Step
import org.apache.commons.lang3.SerializationUtils
import spock.lang.Specification
import spock.lang.Unroll

import java.util.stream.Collectors

@Unroll
class TestInitialFactsCalc extends Specification {


    def "test initial facts calculation"(String serializedPlanFilename,
                                         VariableModelFunction failureModel,
                                         expectedClauses) {
        setup:
        TreeMap<Integer, Set<Step>> plan = SerializationUtils.deserialize(new FileInputStream(
                serializedPlanFilename))
        CnfCompilation cnfCompilation = new CnfCompilation(plan, failureModel)

        expect:
        cnfCompilation.calcInitFacts().stream()
                .map({ val -> val.toString() })
                .sorted()
                .collect(Collectors.toList()) == expectedClauses

        where:
        serializedPlanFilename << [
                'deports0.problem.ser',
                'elevator1.problem.ser',
                'satellite1.problem.ser',
                'satellite20.problem.ser'
        ]
        failureModel << [
                new NoEffectFailureModel(),
                new NoEffectFailureModel(),
                new NoEffectFailureModel(),
                new NoEffectFailureModel()
        ]
        expectedClauses << [
                [
                        "{Stage:-1, State:at~truck0=LOCKED_FOR_UPDATE}=false",
                        "{Stage:-1, State:at~truck0=distributor1}=true",
                        "{Stage:-1, State:at~truck1=LOCKED_FOR_UPDATE}=false",
                        "{Stage:-1, State:at~truck1=depot0}=true",
                        "{Stage:-1, State:clear~crate0=LOCKED_FOR_UPDATE}=false",
                        "{Stage:-1, State:clear~crate0=true}=true",
                        "{Stage:-1, State:clear~crate1=LOCKED_FOR_UPDATE}=false",
                        "{Stage:-1, State:clear~crate1=true}=true",
                        "{Stage:-1, State:clear~hoist0=LOCKED_FOR_UPDATE}=false",
                        "{Stage:-1, State:clear~hoist0=true}=true",
                        "{Stage:-1, State:clear~hoist1=LOCKED_FOR_UPDATE}=false",
                        "{Stage:-1, State:clear~hoist1=true}=true",
                        "{Stage:-1, State:clear~hoist2=LOCKED_FOR_UPDATE}=false",
                        "{Stage:-1, State:clear~hoist2=true}=true",
                        "{Stage:-1, State:clear~pallet0=LOCKED_FOR_UPDATE}=false",
                        "{Stage:-1, State:clear~pallet0=false}=true",
                        "{Stage:-1, State:clear~pallet1=LOCKED_FOR_UPDATE}=false",
                        "{Stage:-1, State:clear~pallet1=false}=true",
                        "{Stage:-1, State:clear~pallet2=LOCKED_FOR_UPDATE}=false",
                        "{Stage:-1, State:clear~pallet2=true}=true",
                        "{Stage:-1, State:on~crate0=LOCKED_FOR_UPDATE}=false",
                        "{Stage:-1, State:on~crate0=pallet1}=true",
                        "{Stage:-1, State:on~crate1=LOCKED_FOR_UPDATE}=false",
                        "{Stage:-1, State:on~crate1=pallet0}=true",
                        "{Stage:-1, State:pos~crate0=LOCKED_FOR_UPDATE}=false",
                        "{Stage:-1, State:pos~crate0=distributor0}=true",
                        "{Stage:-1, State:pos~crate1=LOCKED_FOR_UPDATE}=false",
                        "{Stage:-1, State:pos~crate1=depot0}=true",
                ],
                [
                        "{Stage:-1, State:at~p0=LOCKED_FOR_UPDATE}=false",
                        "{Stage:-1, State:at~p0=n8}=true",
                        "{Stage:-1, State:at~p1=LOCKED_FOR_UPDATE}=false",
                        "{Stage:-1, State:at~p1=n3}=true",
                        "{Stage:-1, State:at~p2=LOCKED_FOR_UPDATE}=false",
                        "{Stage:-1, State:at~p2=n2}=true",
                        "{Stage:-1, State:lift-at~fast0=LOCKED_FOR_UPDATE}=false",
                        "{Stage:-1, State:lift-at~fast0=n0}=true",
                        "{Stage:-1, State:lift-at~slow0-0=LOCKED_FOR_UPDATE}=false",
                        "{Stage:-1, State:lift-at~slow0-0=n2}=true",
                        "{Stage:-1, State:lift-at~slow1-0=LOCKED_FOR_UPDATE}=false",
                        "{Stage:-1, State:lift-at~slow1-0=n4}=true",
                        "{Stage:-1, State:passengers~fast0=LOCKED_FOR_UPDATE}=false",
                        "{Stage:-1, State:passengers~fast0=n0}=true",
                        "{Stage:-1, State:passengers~slow0-0=LOCKED_FOR_UPDATE}=false",
                        "{Stage:-1, State:passengers~slow0-0=n0}=true",
                        "{Stage:-1, State:passengers~slow1-0=LOCKED_FOR_UPDATE}=false",
                        "{Stage:-1, State:passengers~slow1-0=n0}=true",
                ],
                [
                        "{Stage:-1, State:calibrated~instrument0=LOCKED_FOR_UPDATE}=false",
                        "{Stage:-1, State:calibrated~instrument0=false}=true",
                        "{Stage:-1, State:pointing~satellite0=LOCKED_FOR_UPDATE}=false",
                        "{Stage:-1, State:pointing~satellite0=phenomenon6}=true",
                        "{Stage:-1, State:power_avail~satellite0=LOCKED_FOR_UPDATE}=false",
                        "{Stage:-1, State:power_avail~satellite0=true}=true",
                        "{Stage:-1, State:power_on~instrument0=LOCKED_FOR_UPDATE}=false",
                        "{Stage:-1, State:power_on~instrument0=false}=true",

                ],
                [
                        "{Stage:-1, State:calibrated~instrument0=LOCKED_FOR_UPDATE}=false",
                        "{Stage:-1, State:calibrated~instrument0=false}=true",
                        "{Stage:-1, State:calibrated~instrument10=LOCKED_FOR_UPDATE}=false",
                        "{Stage:-1, State:calibrated~instrument10=false}=true",
                        "{Stage:-1, State:calibrated~instrument11=LOCKED_FOR_UPDATE}=false",
                        "{Stage:-1, State:calibrated~instrument11=false}=true",
                        "{Stage:-1, State:calibrated~instrument12=LOCKED_FOR_UPDATE}=false",
                        "{Stage:-1, State:calibrated~instrument12=false}=true",
                        "{Stage:-1, State:calibrated~instrument13=LOCKED_FOR_UPDATE}=false",
                        "{Stage:-1, State:calibrated~instrument13=false}=true",
                        "{Stage:-1, State:calibrated~instrument14=LOCKED_FOR_UPDATE}=false",
                        "{Stage:-1, State:calibrated~instrument14=false}=true",
                        "{Stage:-1, State:calibrated~instrument15=LOCKED_FOR_UPDATE}=false",
                        "{Stage:-1, State:calibrated~instrument15=false}=true",
                        "{Stage:-1, State:calibrated~instrument16=LOCKED_FOR_UPDATE}=false",
                        "{Stage:-1, State:calibrated~instrument16=false}=true",
                        "{Stage:-1, State:calibrated~instrument17=LOCKED_FOR_UPDATE}=false",
                        "{Stage:-1, State:calibrated~instrument17=false}=true",
                        "{Stage:-1, State:calibrated~instrument18=LOCKED_FOR_UPDATE}=false",
                        "{Stage:-1, State:calibrated~instrument18=false}=true",
                        "{Stage:-1, State:calibrated~instrument19=LOCKED_FOR_UPDATE}=false",
                        "{Stage:-1, State:calibrated~instrument19=false}=true",
                        "{Stage:-1, State:calibrated~instrument1=LOCKED_FOR_UPDATE}=false",
                        "{Stage:-1, State:calibrated~instrument1=false}=true",
                        "{Stage:-1, State:calibrated~instrument20=LOCKED_FOR_UPDATE}=false",
                        "{Stage:-1, State:calibrated~instrument20=false}=true",
                        "{Stage:-1, State:calibrated~instrument21=LOCKED_FOR_UPDATE}=false",
                        "{Stage:-1, State:calibrated~instrument21=false}=true",
                        "{Stage:-1, State:calibrated~instrument22=LOCKED_FOR_UPDATE}=false",
                        "{Stage:-1, State:calibrated~instrument22=false}=true",
                        "{Stage:-1, State:calibrated~instrument23=LOCKED_FOR_UPDATE}=false",
                        "{Stage:-1, State:calibrated~instrument23=false}=true",
                        "{Stage:-1, State:calibrated~instrument24=LOCKED_FOR_UPDATE}=false",
                        "{Stage:-1, State:calibrated~instrument24=false}=true",
                        "{Stage:-1, State:calibrated~instrument25=LOCKED_FOR_UPDATE}=false",
                        "{Stage:-1, State:calibrated~instrument25=false}=true",
                        "{Stage:-1, State:calibrated~instrument26=LOCKED_FOR_UPDATE}=false",
                        "{Stage:-1, State:calibrated~instrument26=false}=true",
                        "{Stage:-1, State:calibrated~instrument27=LOCKED_FOR_UPDATE}=false",
                        "{Stage:-1, State:calibrated~instrument27=false}=true",
                        "{Stage:-1, State:calibrated~instrument28=LOCKED_FOR_UPDATE}=false",
                        "{Stage:-1, State:calibrated~instrument28=false}=true",
                        "{Stage:-1, State:calibrated~instrument2=LOCKED_FOR_UPDATE}=false",
                        "{Stage:-1, State:calibrated~instrument2=false}=true",
                        "{Stage:-1, State:calibrated~instrument3=LOCKED_FOR_UPDATE}=false",
                        "{Stage:-1, State:calibrated~instrument3=false}=true",
                        "{Stage:-1, State:calibrated~instrument4=LOCKED_FOR_UPDATE}=false",
                        "{Stage:-1, State:calibrated~instrument4=false}=true",
                        "{Stage:-1, State:calibrated~instrument5=LOCKED_FOR_UPDATE}=false",
                        "{Stage:-1, State:calibrated~instrument5=false}=true",
                        "{Stage:-1, State:calibrated~instrument6=LOCKED_FOR_UPDATE}=false",
                        "{Stage:-1, State:calibrated~instrument6=false}=true",
                        "{Stage:-1, State:calibrated~instrument7=LOCKED_FOR_UPDATE}=false",
                        "{Stage:-1, State:calibrated~instrument7=false}=true",
                        "{Stage:-1, State:calibrated~instrument8=LOCKED_FOR_UPDATE}=false",
                        "{Stage:-1, State:calibrated~instrument8=false}=true",
                        "{Stage:-1, State:calibrated~instrument9=LOCKED_FOR_UPDATE}=false",
                        "{Stage:-1, State:calibrated~instrument9=false}=true",
                        "{Stage:-1, State:have_image~phenomenon12~image4=LOCKED_FOR_UPDATE}=false",
                        "{Stage:-1, State:have_image~phenomenon12~image4=false}=true",
                        "{Stage:-1, State:have_image~phenomenon14~thermograph7=LOCKED_FOR_UPDATE}=false",
                        "{Stage:-1, State:have_image~phenomenon14~thermograph7=false}=true",
                        "{Stage:-1, State:have_image~phenomenon19~image2=LOCKED_FOR_UPDATE}=false",
                        "{Stage:-1, State:have_image~phenomenon19~image2=false}=true",
                        "{Stage:-1, State:have_image~phenomenon19~image4=LOCKED_FOR_UPDATE}=false",
                        "{Stage:-1, State:have_image~phenomenon19~image4=false}=true",
                        "{Stage:-1, State:have_image~phenomenon21~image2=LOCKED_FOR_UPDATE}=false",
                        "{Stage:-1, State:have_image~phenomenon21~image2=false}=true",
                        "{Stage:-1, State:have_image~phenomenon21~image4=LOCKED_FOR_UPDATE}=false",
                        "{Stage:-1, State:have_image~phenomenon21~image4=false}=true",
                        "{Stage:-1, State:have_image~phenomenon21~thermograph7=LOCKED_FOR_UPDATE}=false",
                        "{Stage:-1, State:have_image~phenomenon21~thermograph7=false}=true",
                        "{Stage:-1, State:have_image~phenomenon5~image3=LOCKED_FOR_UPDATE}=false",
                        "{Stage:-1, State:have_image~phenomenon5~image3=false}=true",
                        "{Stage:-1, State:have_image~phenomenon5~spectrograph0=LOCKED_FOR_UPDATE}=false",
                        "{Stage:-1, State:have_image~phenomenon5~spectrograph0=false}=true",
                        "{Stage:-1, State:have_image~phenomenon5~thermograph8=LOCKED_FOR_UPDATE}=false",
                        "{Stage:-1, State:have_image~phenomenon5~thermograph8=false}=true",
                        "{Stage:-1, State:have_image~phenomenon8~infrared5=LOCKED_FOR_UPDATE}=false",
                        "{Stage:-1, State:have_image~phenomenon8~infrared5=false}=true",
                        "{Stage:-1, State:have_image~phenomenon8~spectrograph6=LOCKED_FOR_UPDATE}=false",
                        "{Stage:-1, State:have_image~phenomenon8~spectrograph6=false}=true",
                        "{Stage:-1, State:have_image~phenomenon8~thermograph7=LOCKED_FOR_UPDATE}=false",
                        "{Stage:-1, State:have_image~phenomenon8~thermograph7=false}=true",
                        "{Stage:-1, State:have_image~planet13~image2=LOCKED_FOR_UPDATE}=false",
                        "{Stage:-1, State:have_image~planet13~image2=false}=true",
                        "{Stage:-1, State:have_image~planet13~infrared5=LOCKED_FOR_UPDATE}=false",
                        "{Stage:-1, State:have_image~planet13~infrared5=false}=true",
                        "{Stage:-1, State:have_image~planet13~spectrograph6=LOCKED_FOR_UPDATE}=false",
                        "{Stage:-1, State:have_image~planet13~spectrograph6=false}=true",
                        "{Stage:-1, State:have_image~planet15~image3=LOCKED_FOR_UPDATE}=false",
                        "{Stage:-1, State:have_image~planet15~image3=false}=true",
                        "{Stage:-1, State:have_image~planet18~infrared5=LOCKED_FOR_UPDATE}=false",
                        "{Stage:-1, State:have_image~planet18~infrared5=false}=true",
                        "{Stage:-1, State:have_image~planet18~infrared9=LOCKED_FOR_UPDATE}=false",
                        "{Stage:-1, State:have_image~planet18~infrared9=false}=true",
                        "{Stage:-1, State:have_image~planet18~thermograph7=LOCKED_FOR_UPDATE}=false",
                        "{Stage:-1, State:have_image~planet18~thermograph7=false}=true",
                        "{Stage:-1, State:have_image~planet22~image2=LOCKED_FOR_UPDATE}=false",
                        "{Stage:-1, State:have_image~planet22~image2=false}=true",
                        "{Stage:-1, State:have_image~planet22~spectrograph6=LOCKED_FOR_UPDATE}=false",
                        "{Stage:-1, State:have_image~planet22~spectrograph6=false}=true",
                        "{Stage:-1, State:have_image~planet7~image2=LOCKED_FOR_UPDATE}=false",
                        "{Stage:-1, State:have_image~planet7~image2=false}=true",
                        "{Stage:-1, State:have_image~planet7~infrared5=LOCKED_FOR_UPDATE}=false",
                        "{Stage:-1, State:have_image~planet7~infrared5=false}=true",
                        "{Stage:-1, State:have_image~planet7~spectrograph6=LOCKED_FOR_UPDATE}=false",
                        "{Stage:-1, State:have_image~planet7~spectrograph6=false}=true",
                        "{Stage:-1, State:have_image~planet9~spectrograph6=LOCKED_FOR_UPDATE}=false",
                        "{Stage:-1, State:have_image~planet9~spectrograph6=false}=true",
                        "{Stage:-1, State:have_image~star10~spectrograph6=LOCKED_FOR_UPDATE}=false",
                        "{Stage:-1, State:have_image~star10~spectrograph6=false}=true",
                        "{Stage:-1, State:have_image~star11~image3=LOCKED_FOR_UPDATE}=false",
                        "{Stage:-1, State:have_image~star11~image3=false}=true",
                        "{Stage:-1, State:have_image~star11~image4=LOCKED_FOR_UPDATE}=false",
                        "{Stage:-1, State:have_image~star11~image4=false}=true",
                        "{Stage:-1, State:have_image~star11~thermograph7=LOCKED_FOR_UPDATE}=false",
                        "{Stage:-1, State:have_image~star11~thermograph7=false}=true",
                        "{Stage:-1, State:have_image~star16~image3=LOCKED_FOR_UPDATE}=false",
                        "{Stage:-1, State:have_image~star16~image3=false}=true",
                        "{Stage:-1, State:have_image~star16~image4=LOCKED_FOR_UPDATE}=false",
                        "{Stage:-1, State:have_image~star16~image4=false}=true",
                        "{Stage:-1, State:have_image~star20~spectrograph0=LOCKED_FOR_UPDATE}=false",
                        "{Stage:-1, State:have_image~star20~spectrograph0=false}=true",
                        "{Stage:-1, State:have_image~star23~image2=LOCKED_FOR_UPDATE}=false",
                        "{Stage:-1, State:have_image~star23~image2=false}=true",
                        "{Stage:-1, State:have_image~star23~infrared9=LOCKED_FOR_UPDATE}=false",
                        "{Stage:-1, State:have_image~star23~infrared9=false}=true",
                        "{Stage:-1, State:have_image~star24~infrared5=LOCKED_FOR_UPDATE}=false",
                        "{Stage:-1, State:have_image~star24~infrared5=false}=true",
                        "{Stage:-1, State:have_image~star24~spectrograph6=LOCKED_FOR_UPDATE}=false",
                        "{Stage:-1, State:have_image~star24~spectrograph6=false}=true",
                        "{Stage:-1, State:have_image~star6~image3=LOCKED_FOR_UPDATE}=false",
                        "{Stage:-1, State:have_image~star6~image3=false}=true",
                        "{Stage:-1, State:have_image~star6~spectrograph0=LOCKED_FOR_UPDATE}=false",
                        "{Stage:-1, State:have_image~star6~spectrograph0=false}=true",
                        "{Stage:-1, State:have_image~star6~spectrograph6=LOCKED_FOR_UPDATE}=false",
                        "{Stage:-1, State:have_image~star6~spectrograph6=false}=true",
                        "{Stage:-1, State:pointing~satellite0=LOCKED_FOR_UPDATE}=false",
                        "{Stage:-1, State:pointing~satellite0=groundstation1}=true",
                        "{Stage:-1, State:pointing~satellite1=LOCKED_FOR_UPDATE}=false",
                        "{Stage:-1, State:pointing~satellite1=phenomenon19}=true",
                        "{Stage:-1, State:pointing~satellite2=LOCKED_FOR_UPDATE}=false",
                        "{Stage:-1, State:pointing~satellite2=phenomenon14}=true",
                        "{Stage:-1, State:pointing~satellite3=LOCKED_FOR_UPDATE}=false",
                        "{Stage:-1, State:pointing~satellite3=star10}=true",
                        "{Stage:-1, State:pointing~satellite4=LOCKED_FOR_UPDATE}=false",
                        "{Stage:-1, State:pointing~satellite4=star16}=true",
                        "{Stage:-1, State:power_avail~satellite0=LOCKED_FOR_UPDATE}=false",
                        "{Stage:-1, State:power_avail~satellite0=true}=true",
                        "{Stage:-1, State:power_avail~satellite1=LOCKED_FOR_UPDATE}=false",
                        "{Stage:-1, State:power_avail~satellite1=true}=true",
                        "{Stage:-1, State:power_avail~satellite2=LOCKED_FOR_UPDATE}=false",
                        "{Stage:-1, State:power_avail~satellite2=true}=true",
                        "{Stage:-1, State:power_avail~satellite3=LOCKED_FOR_UPDATE}=false",
                        "{Stage:-1, State:power_avail~satellite3=true}=true",
                        "{Stage:-1, State:power_avail~satellite4=LOCKED_FOR_UPDATE}=false",
                        "{Stage:-1, State:power_avail~satellite4=true}=true",
                        "{Stage:-1, State:power_on~instrument0=LOCKED_FOR_UPDATE}=false",
                        "{Stage:-1, State:power_on~instrument0=false}=true",
                        "{Stage:-1, State:power_on~instrument10=LOCKED_FOR_UPDATE}=false",
                        "{Stage:-1, State:power_on~instrument10=false}=true",
                        "{Stage:-1, State:power_on~instrument11=LOCKED_FOR_UPDATE}=false",
                        "{Stage:-1, State:power_on~instrument11=false}=true",
                        "{Stage:-1, State:power_on~instrument12=LOCKED_FOR_UPDATE}=false",
                        "{Stage:-1, State:power_on~instrument12=false}=true",
                        "{Stage:-1, State:power_on~instrument13=LOCKED_FOR_UPDATE}=false",
                        "{Stage:-1, State:power_on~instrument13=false}=true",
                        "{Stage:-1, State:power_on~instrument14=LOCKED_FOR_UPDATE}=false",
                        "{Stage:-1, State:power_on~instrument14=false}=true",
                        "{Stage:-1, State:power_on~instrument15=LOCKED_FOR_UPDATE}=false",
                        "{Stage:-1, State:power_on~instrument15=false}=true",
                        "{Stage:-1, State:power_on~instrument16=LOCKED_FOR_UPDATE}=false",
                        "{Stage:-1, State:power_on~instrument16=false}=true",
                        "{Stage:-1, State:power_on~instrument17=LOCKED_FOR_UPDATE}=false",
                        "{Stage:-1, State:power_on~instrument17=false}=true",
                        "{Stage:-1, State:power_on~instrument18=LOCKED_FOR_UPDATE}=false",
                        "{Stage:-1, State:power_on~instrument18=false}=true",
                        "{Stage:-1, State:power_on~instrument19=LOCKED_FOR_UPDATE}=false",
                        "{Stage:-1, State:power_on~instrument19=false}=true",
                        "{Stage:-1, State:power_on~instrument1=LOCKED_FOR_UPDATE}=false",
                        "{Stage:-1, State:power_on~instrument1=false}=true",
                        "{Stage:-1, State:power_on~instrument20=LOCKED_FOR_UPDATE}=false",
                        "{Stage:-1, State:power_on~instrument20=false}=true",
                        "{Stage:-1, State:power_on~instrument21=LOCKED_FOR_UPDATE}=false",
                        "{Stage:-1, State:power_on~instrument21=false}=true",
                        "{Stage:-1, State:power_on~instrument22=LOCKED_FOR_UPDATE}=false",
                        "{Stage:-1, State:power_on~instrument22=false}=true",
                        "{Stage:-1, State:power_on~instrument23=LOCKED_FOR_UPDATE}=false",
                        "{Stage:-1, State:power_on~instrument23=false}=true",
                        "{Stage:-1, State:power_on~instrument24=LOCKED_FOR_UPDATE}=false",
                        "{Stage:-1, State:power_on~instrument24=false}=true",
                        "{Stage:-1, State:power_on~instrument25=LOCKED_FOR_UPDATE}=false",
                        "{Stage:-1, State:power_on~instrument25=false}=true",
                        "{Stage:-1, State:power_on~instrument26=LOCKED_FOR_UPDATE}=false",
                        "{Stage:-1, State:power_on~instrument26=false}=true",
                        "{Stage:-1, State:power_on~instrument27=LOCKED_FOR_UPDATE}=false",
                        "{Stage:-1, State:power_on~instrument27=false}=true",
                        "{Stage:-1, State:power_on~instrument28=LOCKED_FOR_UPDATE}=false",
                        "{Stage:-1, State:power_on~instrument28=false}=true",
                        "{Stage:-1, State:power_on~instrument2=LOCKED_FOR_UPDATE}=false",
                        "{Stage:-1, State:power_on~instrument2=false}=true",
                        "{Stage:-1, State:power_on~instrument3=LOCKED_FOR_UPDATE}=false",
                        "{Stage:-1, State:power_on~instrument3=false}=true",
                        "{Stage:-1, State:power_on~instrument4=LOCKED_FOR_UPDATE}=false",
                        "{Stage:-1, State:power_on~instrument4=false}=true",
                        "{Stage:-1, State:power_on~instrument5=LOCKED_FOR_UPDATE}=false",
                        "{Stage:-1, State:power_on~instrument5=false}=true",
                        "{Stage:-1, State:power_on~instrument6=LOCKED_FOR_UPDATE}=false",
                        "{Stage:-1, State:power_on~instrument6=false}=true",
                        "{Stage:-1, State:power_on~instrument7=LOCKED_FOR_UPDATE}=false",
                        "{Stage:-1, State:power_on~instrument7=false}=true",
                        "{Stage:-1, State:power_on~instrument8=LOCKED_FOR_UPDATE}=false",
                        "{Stage:-1, State:power_on~instrument8=false}=true",
                        "{Stage:-1, State:power_on~instrument9=LOCKED_FOR_UPDATE}=false",
                        "{Stage:-1, State:power_on~instrument9=false}=true",
                        
                ]


        ]
    }


}